version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    command: sh -c "alembic -c /alembic.ini upgrade head && uvicorn app.main:api --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DEBUG=1
    volumes:
      - ./src:/app
      - ./alembic.ini:/alembic.ini
      - ./alembic:/alembic
      - ./src/app/data/photos:/app/app/data/photos
      - ./data/db:/data/db
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - redis

  celery_worker:
    build: .
    working_dir: /app
    command: celery -A app.tasks worker --loglevel=info
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./src:/app
      - ./alembic.ini:/app/alembic.ini
      - ./alembic:/app/alembic
      - ./src/app/data/photos:/app/app/data/photos
      - ./data/db:/data/db
    depends_on:
      - redis

  redis:
    image: redis:alpine
