"""Change database layout

Revision ID: 6d1592c07192
Revises: 297d0864c87e
Create Date: 2025-07-22 11:18:55.082319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1592c07192'
down_revision: Union[str, None] = '297d0864c87e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identification_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('ai_classification', sa.Text(), nullable=True),
    sa.Column('expert_classification', sa.Text(), nullable=True),
    sa.Column('annotations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id')
    )
    op.create_index(op.f('ix_identification_tasks_id'), 'identification_tasks', ['id'], unique=False)
    op.drop_column('observations', 'ai_classification')
    op.drop_column('observations', 'expert_classification')
    op.drop_column('observations', 'annotations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('annotations', sa.TEXT(), nullable=True))
    op.add_column('observations', sa.Column('expert_classification', sa.TEXT(), nullable=True))
    op.add_column('observations', sa.Column('ai_classification', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_identification_tasks_id'), table_name='identification_tasks')
    op.drop_table('identification_tasks')
    # ### end Alembic commands ###
